# Generated by Django 2.2.3 on 2019-07-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='genres',
            new_name='genre',
        ),
    ]
